<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ulrich Karl ODJO, Alexandra MILLOT">

<title>Projet 3: Etude de la date de maturation du Merlot</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="ecsa_files/libs/clipboard/clipboard.min.js"></script>
<script src="ecsa_files/libs/quarto-html/quarto.js"></script>
<script src="ecsa_files/libs/quarto-html/popper.min.js"></script>
<script src="ecsa_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ecsa_files/libs/quarto-html/anchor.min.js"></script>
<link href="ecsa_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ecsa_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ecsa_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ecsa_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ecsa_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="ecsa_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="ecsa_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<link rel="stylesheet" href="style.css">
</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Projet 3: Etude de la date de maturation du Merlot</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ulrich Karl ODJO, Alexandra MILLOT </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Merlot.jpg" class="img-fluid figure-img"></p>
</figure>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>À Bordeaux, les viticulteurs ont sur plusieurs années étudiées les conditions de développement et de maturation de leurs différents cépages en fonction des sols de leur terre, afin d’aménager au mieux leurs cultures. Pour exemple, le merlot est un cépage rouge, aux petites baies noires apparues à la fin du XVIIIe siècle. Ce cépage est produit dans la plupart des terroirs bordelais, où il représente plus de 65% de la surface plantée. Le merlot est à maturation lente estimée à deux semaines et demie après le Chasselas (cépage blanc d’origine suisse). Plus la date de maturation est tardive plus le vin est meilleur. D’après les études menées par les viticulteurs en collaboration avec des géologues, les sols les plus adaptés à une maturation lente sont les sols argilo-calcaires frais. Malgré avoir étudier scrupuleusement l’emplacement du merlot sur leur terre, les viticulteurs ont constaté qu’au fil des années la date de maturation pouvait varier considérablement d’une année à l’autre et que celle-ci arrivait de plus en plus tôt dans l’année, ce qui est problématique en matière de logistique et qualité du vin.</p>
<p>La variation de cette date d’une année à l’autre se constate sur le graphique ci-dessous :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/graph.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>Les viticulteurs cherchent à pouvoir estimer la date de maturation des Merlots afin de simplifier leur logistique.</p>
<p>Cette date n’est pas facile à prédir en raison de divers facteurs qui en viennent à la faire fluctuer. Bien connu, le mode de vie de notre société impact considérablement l’environnement. Depuis plusieurs années, les conséquences du réchauffement climatique, de la pollution de l’air et des sols deviennent de plus en plus fréquentes : la sècheresse, les feux de forêts, les inodations, la fonte des glaciers etc.</p>
<p>Nous nous intéressons dans cette étude de cas aux facteurs climatiques, tel que, les phénomènes météorologiques. En effet, le réchauffement climatique entraine à travers les années une augmentation du nombre de jours et de nuits “chauds” (au-dessus de 20°C). Cela aurait comme impact le retardement de la date de récolte des vignes.</p>
<p>Pour ces raisons, les viticulteurs font appel à des spécialistes en analyse de données statistiques, afin de répondre à la problématique suivante :</p>
<p><strong>Quels sont les facteurs climatiques influençant la date de maturation du merlot ?</strong></p>
<p>Pour répondre à cette problématique, nous introduirons cette étude par une explication du cycle de développement du merlot, afin de comprendre au mieux les conditions de son développement. Par la suite, nous expliquerons les variables utilisées, pour faciliter la lecture de ce rapport. L’analyse commencera par l’interprétation de la matrice de corrélation regroupant toutes les variables de ce jeu de donnéés.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chargement des packages nécéssaires</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chargement du dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>vigne <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"ECSA3_vignobles_bordelais2022.xlsx"</span>, <span class="at">sheet=</span><span class="dv">2</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppression de la variable redondante</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>vigne <span class="ot">&lt;-</span> vigne <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(MaMerlot...<span class="dv">19</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Renomme la première variable</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>vigne <span class="ot">&lt;-</span> vigne <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">MaMerlot=</span>MaMerlot...<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="le-merlot-et-son-environnement" class="level2">
<h2 class="anchored" data-anchor-id="le-merlot-et-son-environnement">Le merlot et son environnement</h2>
<p>Le merlot se développe selon un cycle précis. À la fin de la maturation, courant septembre, le merlot se met en dormance correspondant à l’hibernation pendant l’hiver, pour ce protégé du froid et du gel de cette période. La sortie de la dormance s’effectue quand les températures avoisinent les 10°C. Petit à petit, la vigne va sortir de son état végétatif, en réactivant la circulation de la sève. Deux jours après le Chasselas le cépage débourre, c’est-à-dire qu’il forme des bourgeons. Durant le mois d’avril, des feuilles vont pousser sur la vigne, afin de commencer la photosynthèse, pour la formation de composés organiques essentiels à la plante, dont le sucre. S’ensuit la floraison, étant à l’origine de la fécondation des vignes, aboutissants aux graines contenues dans les raisins. Puis la nouaison, formation des grains de raisons. Ces graines grossissent et changent de couleur par la suite, c’est le phénomène de véraison. Pour parvenir, deux semaines et demie après le Chasselas à la maturation, se déterminant à partir de la sucrosité des baies (taux de sucre).</p>
<p>Pour avoir une idée exacte des périodes où se produisent la floraison, la véraison et la maturation voici quelques statistiques :</p>
<p><span style="color:purple"><strong>Floraison :</strong></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vigne<span class="sc">$</span>floraison)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  143.0   155.0   162.0   161.4   166.0   178.0      20 </code></pre>
</div>
</div>
<p><span style="color:purple"><strong>Veraison :</strong></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vigne<span class="sc">$</span>Veraison)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  211.5   221.4   228.7   228.8   234.6   247.3       7 </code></pre>
</div>
</div>
<p><span style="color:purple"><strong>Maturation :</strong></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vigne<span class="sc">$</span>MaMerlot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  252.0   259.5   269.8   268.2   275.7   288.2       7 </code></pre>
</div>
</div>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<p>Pour bien commencer cette étude de cas il est important d’expliquer les différentes variables qui constituent le jeu de données :</p>
<ul>
<li><code>MaMerlot</code> : Date en jours julien de maturité du merlot.</li>
<li><code>NbJrs30JJ</code>/<code>NbJrs30JuS</code> : Nombre de jours où il a fait une température supérieur à 30 degré de janvier à juin (JJ) / de juillet à septembre (JuS)</li>
<li><code>NbJ25_30JJ</code>/<code>NbJ25_30JuS</code> : Nombre de jours où il a fait une température entre 25 et 30 degré de janvier à juin (JJ) / de juillet à septembre (JuS)</li>
</ul>
<p>Le principe est le même pour les variables : <code>NbJ20_25JJ</code> / <code>NbJ15_20JJ</code> / <code>NbJ10_15JJ</code> / <code>NbJ20_25JuS</code> / <code>NbJ15_20JuS</code> / <code>NbJ10_15JuS</code></p>
<ul>
<li><code>SommeTs10JJ</code>/<code>SommeTs10JuS</code> : Somme des températures supérieur à 10 degré de janvier à juin (JJ) / de juillet à septembre (JuS).</li>
<li><code>SommePluviometrieJJ</code>/<code>SommePluviometrieJuS</code> : Somme de pluviométrie de janvier à juin (JJ) / de juillet à septembre (JuS)</li>
<li><code>SommeRayonnementJJ</code>/<code>SommeRayonnementJuS</code> : Somme de rayonnement solaire de janvier à juin (JJ) / de juillet à septembre (JuS)</li>
<li><code>Veraison</code> : Date en jours julien de veraison du merlot.</li>
<li><code>Floraison</code> : Date en jours julien de floraison du merlot.</li>
</ul>
</section>
<section id="corrélation" class="level2">
<h2 class="anchored" data-anchor-id="corrélation">1. Corrélation</h2>
<p>Dans cette partie nous allons effectuer une analyse de corrélation. L’analyse de corrélation est une méthode statistique bivariée de mesure de force de la relation linéaire entre deux variables. La corrélation peut-être soit positive, négative ou faible voire nulle. Une corrélation positive entre deux variables signifie que les deux variables évoluent dans le même sens. Tandis qu’une corrélation négative entre deux variables signifie que les variables évoluent dans des directions opposées. S’il n’y a pas de corrélation cela signifie que la variable n’a pas d’influence sur l’autre.</p>
<p>Pour ce faire nous avons effectué une matrice de corrélation mettant en évidence leurs relations linéaires :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">corrplot</span>(<span class="fu">cor</span>(vigne, <span class="at">use=</span><span class="st">"complete.obs"</span>), <span class="at">tl.cex=</span><span class="fl">0.5</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">number.cex=</span><span class="fl">0.5</span>, <span class="at">order=</span><span class="st">"hclust"</span>, <span class="at">tl.col=</span><span class="st">"black"</span>, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">col=</span><span class="fu">COL2</span>(<span class="st">"PRGn"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ecsa_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Les corrélations positives sont affichées en vert et les corrélations négatives en violet L’intensité de la couleur et la taille des cercles sont proportionnelles aux coefficients de corrélation. À droite du corrélogramme, la légende de couleurs montre les coefficients de corrélation et les couleurs correspondantes.</p>
</section>
<section id="interprétation" class="level2">
<h2 class="anchored" data-anchor-id="interprétation">Interprétation</h2>
<p>Portons notre attention sur les variables de maturation des merlots ainsi que sur celles de floraison et de véraison. Ces variables sont corrélées positivement entre elles. Ce qui est évident, car après la floraison s’ensuit la véraison qui entraine la maturation du merlot. Toutes ces phases sont liées à intervalles plus ou moins régulié.</p>
<p>Il est intéressant de mettre en évidence qu’elles sont corrélées négativement avec toutes les variables s’étalant de janvier à juin. Cela s’explique par une phase de dormance raccourcies due à un hiver chaud.</p>
<p>Toujours par rapport aux trois variables : floraison, véraison et maturation. Nous observons que sur la période de juillet à septembre les températures comprises entre 10 et 25 degrés sont corrélées positivement. Il s’agit en effet du temps idéal pour un développement optimal de la vigne. Contrairement, aux températures supérieures à 30°C qui sont corrélées négativement aux trois variables, car elles provoquent la sécheresse dans les vignes.</p>
<p>Le rayonnement et la pluviométrie de juin à septembre, ainsi que de janvier à juin sont corrélés négativement, car s’il y a de la pluie, le soleil ne peut éclairer, et donc la quantité de lumière (mesurée en Lux dans le système international) est plus faible.</p>
<p><span style="color:purple"><strong>Avant de continuer, expliquons plus en détails pourquoi la date de maturation du merlot est corrélée positivement avec le nombre de jours entre 20°C et 25°C sur la période de juin à septembre, et négativement sur la période de janvier à juin.</strong></span></p>
<p>De janvier à juin, la vigne sort lentement de son état de dormance, afin de commencer à créer des bourgeons pour l’été. Cependant, des températures trop chaudes en automne/hiver vont accélérer cette sortie de dormance (nécessaire à la plante, car la protégeant des dégâts liés aux conditions climatiques extrêmes), et donc rendre la vigne vulnérable aux conditions extérieures comme le gel, entraînant la mort de cette dernière. Pour le début de l’été, la plante est déjà sortie de son état de dormance, et le risque de gel est quasi nul, donc plus il fera chaud (sans être extrême, auquel cas la plante mourra de sécheresse), moins il y aura de nuage, et donc plus il y aura de rayonnement pour que la plante effectue la photosynthèse.</p>
</section>
<section id="analyse-globale-de-la-regression" class="level2">
<h2 class="anchored" data-anchor-id="analyse-globale-de-la-regression">2. Analyse globale de la regression</h2>
</section>
<section id="analyse-de-la-regression-globale-et-selection-dun-sous-model" class="level2">
<h2 class="anchored" data-anchor-id="analyse-de-la-regression-globale-et-selection-dun-sous-model">2.1. Analyse de la regression globale et selection d’un sous-model</h2>
<p>Dans le modèle suivant on souhaite tester un ensemble de sous-modèle, sur la base de l’analyse de la corrélation entre différente les différentes variables explicatives et notre variable dépendante <code>MaMerlot</code>.</p>
<p>Tout d’abord nous commençons par une estimation du modèle complet qui nous fournis les résultats suivants :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle de regression globale</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>Mfull <span class="ot">&lt;-</span> <span class="fu">lm</span>(MaMerlot <span class="sc">~</span> ., <span class="at">data =</span> vigne)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(Mfull)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interprétation :</strong> Le modèle complet nous suggère que seule la variable explicative <code>Veraison</code> est significativement différente de zéro et joue un rôle dans l’explication des variations observées de la date de maturation du merlot.</p>
<p>Après cette première estimation du modèle complet, on se propose d’utiliser ici les variables corrélées positivement avec <code>MaMerlot</code> pour essayer d’expliquer les variations des dates de maturation. Le modèle estimé nous donnes ainsi les résultats suivants :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle 1</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MaMerlot <span class="sc">~</span> Veraison <span class="sc">+</span> NbJ10_15JJ <span class="sc">+</span> NbJ10_15JuS <span class="sc">+</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>           NbJ15_20JuS <span class="sc">+</span> NbJ20_25JuS, <span class="at">data =</span> vigne)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MaMerlot ~ Veraison + NbJ10_15JJ + NbJ10_15JuS + 
    NbJ15_20JuS + NbJ20_25JuS, data = vigne)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.5357 -2.8976 -0.9093  2.9390  9.2821 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 60.66103   19.78481   3.066  0.00416 ** 
Veraison     0.89030    0.09637   9.238 6.47e-11 ***
NbJ10_15JJ  -0.01557    0.06761  -0.230  0.81923    
NbJ10_15JuS -1.27347    1.27230  -1.001  0.32374    
NbJ15_20JuS  0.09157    0.15145   0.605  0.54931    
NbJ20_25JuS  0.10039    0.07883   1.273  0.21126    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.242 on 35 degrees of freedom
  (7 observations effacées parce que manquantes)
Multiple R-squared:  0.8318,    Adjusted R-squared:  0.8078 
F-statistic: 34.62 on 5 and 35 DF,  p-value: 1.333e-12</code></pre>
</div>
</div>
<p><strong>Interprétation :</strong> Ce modèle nous suggère comme le modèle complet que seule la variable explicative <code>Veraison</code> est significativement différente de zéro et joue un rôle dans l’explication des variations observées de la date de maturation du merlot. Quand <code>MaMerlot</code> augmente d’une unité <code>Veraison</code> augmente de 0,89 unité.</p>
<p>Ici nous utilisons les variables corrélées négativement avec la date de maturation du Mamerlot pour essayer d’expliquer les variations observées de cette dernière. Le modèle sous-jacent nous donne les résultats suivants :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle 2</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MaMerlot <span class="sc">~</span> NbJ20_25JJ <span class="sc">+</span> NbJrs30JuS <span class="sc">+</span> NbJ25_30JJ, <span class="at">data =</span> vigne)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MaMerlot ~ NbJ20_25JJ + NbJrs30JuS + NbJ25_30JJ, 
    data = vigne)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.7556  -3.8303  -0.9113   3.3400  11.5019 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 296.3822     3.8893  76.204  &lt; 2e-16 ***
NbJ20_25JJ   -0.4474     0.1437  -3.114  0.00356 ** 
NbJrs30JuS   -0.3636     0.1392  -2.612  0.01295 *  
NbJ25_30JJ   -0.9845     0.2198  -4.479 6.96e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.687 on 37 degrees of freedom
  (7 observations effacées parce que manquantes)
Multiple R-squared:  0.6804,    Adjusted R-squared:  0.6545 
F-statistic: 26.26 on 3 and 37 DF,  p-value: 2.825e-09</code></pre>
</div>
</div>
<p><strong>Interprétation :</strong> Ce modèle est intéressant car il suggère que chaque variable explicative joue un rôle dans l’explication de la variable <code>MaMerlot</code>. Dans l’ordre croissant de significativité nous avons <code>NbJrs30JuS</code> puis <code>NbJ20_25JJ</code> et enfin <code>NbJ25_30JJ</code>. On remarque qu’également dans la colonne Estimate les valeurs pour ces trois variables explicatives sont négatives. Cela signifie, que pour <code>NbJ25_30JJ</code> par exemple, quand <code>MaMerlot</code> augmente d’une unité, la variable explicative diminue de 0,98 (≈1) unité. Après interprétation du modèle on peut dire que plus les températures sont élevées, plus la date de maturation du merlot sera précoce, l’impact est plus important pour la période de janvier à juin.</p>
</section>
<section id="selection-dun-modèle-parcimonieux" class="level1">
<h1>2.2. Selection d’un modèle parcimonieux</h1>
<p>Dans cette section, nous souhaitons obtenir un modèle parcimonieux c’est-à-dire ayant peu de variable. Pour ce faire nous devons nous munir d’un critère à prendre en compte pour comparer l’ensemble des modèles qui seront construits. Parmi les critères existant nous pouvons citer le <span class="math inline">C_{p}</span> de Mallows, <span class="math inline">AIC</span>, <span class="math inline">BIC</span>, <span class="math inline">R^{2}_{ajusté}</span>.</p>
<p>Les variables <code>floraison</code> et <code>Veraison</code> étant très corrélées et apportant la même information dans le modèle, nous avions décidé d’en supprimer une pour éviter les problèmes de colinéarités entre les cofacteurs durant le calcul des estimations des <span class="math inline">\hat{\beta}</span>. Pour effectuer notre choix nous nous sommes basé sur la valeur du coefficient de corrélation entre <code>Veraison</code> et <code>Mamerlot</code>, puis entre <code>floraison</code> et <code>Mamerlot</code> en sélectionnant celui avec la valeur de <span class="math inline">r^2</span> la plus élevée. De ce fait nous avions retenu la variable <code>Veraison</code> car elle a le coefficient de corrélation le plus élevé avec notre variable dépendante.</p>
<p>De plus nous avions également retiré la variable <code>NbJ10_15JuS</code> de l’analyse car elle n’apporte pas assez d’information pour prédire la variable <code>MaMerlot</code>. En effet on peut remarquer que cette variable prend en grande majorité la valeur 0. Cela se remarque aussi au niveau des statistiques descriptives avec la médiane qui est 0, de plus au regard de la valeur minimale qui est 0 et maximale qui 3, cette variable ne présente pas de grosse variation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppression de la variable floraison</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>vigne <span class="ot">&lt;-</span> vigne <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(floraison, NbJ10_15JuS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ici nous effectuons une recherche <strong>exhaustive</strong> de tous les meilleurs modèles de chaque taille afin d’en sélectionner celui qui nous semble le plus pertinent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recherche exhaustives des variables pertinentes pour les critères</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Cp/AIC, BIC, R2_ajusté, RSS</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>modelfit.full <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(MaMerlot <span class="sc">~</span> ., <span class="at">data=</span>vigne, <span class="at">nvmax =</span> <span class="dv">10</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>model.full.summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelfit.full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombres de variables optimal pour chaque critères Cp, BIC, R2_ajusté</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>min.cp <span class="ot">&lt;-</span> <span class="fu">which.min</span>(model.full.summary<span class="sc">$</span>cp)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>min.bic <span class="ot">&lt;-</span> <span class="fu">which.min</span>(model.full.summary<span class="sc">$</span>bic)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>max.r2ajuste <span class="ot">&lt;-</span> <span class="fu">which.max</span>(model.full.summary<span class="sc">$</span>adjr2)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(min.cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(min.bic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(max.r2ajuste)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
</div>
<p>La sortie précédente nous donnes le nombre de variables optimales qui minimise ou maximise le critère de sélection choisi. Pour le critère <span class="math inline">C_{p}</span> le meilleur modèle minimisant ce critère contient 5 variables, pour le critère <span class="math inline">BIC</span> c’est 3 variables et pour le <span class="math inline">R^{2}_{ajus}</span> 7 variables permettent de maximiser ce critère.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valeurs du Cp pour chaque modèle de taille considéré</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>cp.val <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(model.full.summary<span class="sc">$</span>cp)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>cp.val <span class="ot">&lt;-</span> cp.val <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">index=</span><span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(cp.val)))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>cp.val <span class="ot">&lt;-</span> cp.val <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">cp=</span><span class="st">`</span><span class="at">model.full.summary$cp</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Représentation graphique</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>cp.val <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(cp) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> index, <span class="at">y =</span> cp)) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#E69F00"</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#E69F00"</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cp"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nombres de variables"</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Cp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ecsa_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valeurs du BIC pour chaque modèle de taille considéré</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>bic.val <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(model.full.summary<span class="sc">$</span>bic)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>bic.val <span class="ot">&lt;-</span> bic.val <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">index=</span><span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(bic.val)))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>bic.val <span class="ot">&lt;-</span> bic.val <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">bic=</span><span class="st">`</span><span class="at">model.full.summary$bic</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Représentation graphique</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>bic.val <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(bic) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> index, <span class="at">y =</span> bic)) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"BIC"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nombres de variables"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"BIC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ecsa_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valeurs du R2 ajusté pour chaque modèle de taille considéré</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>r2.val <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(model.full.summary<span class="sc">$</span>adjr2)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>r2.val <span class="ot">&lt;-</span> r2.val <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">index=</span><span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(r2.val)))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>r2.val <span class="ot">&lt;-</span> r2.val <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">r2=</span><span class="st">`</span><span class="at">model.full.summary$adjr2</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>r2.val <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(r2) <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> index, <span class="at">y =</span> r2)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#E69F00"</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#E69F00"</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"R2 ajusté"</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nombres de variables"</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"R2 ajusté"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ecsa_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Les graphiques précédents nous permettent d’observer l’évolution des différents critères de sélection de variables, en fonction du nombre de variables retenues, et nous pouvons constater de ce fait confirmé les résultats précédents observé de façon analytique.</p>
<p>Dans la suite nous affichons les variables sélectionnées par les différents critères de sélection.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Listes des variables sélectionnées pour le critère Cp</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which</span>(model.full.summary<span class="sc">$</span>which[min.cp, ]<span class="sc">==</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "(Intercept)" "AN"          "NbJ10_15JJ"  "SommeTs10JJ" "NbJ20_25JuS"
[6] "Veraison"   </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Listes des variables sélectionnées pour le critère BIC</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which</span>(model.full.summary<span class="sc">$</span>which[min.bic, ]<span class="sc">==</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "(Intercept)" "AN"          "NbJ20_25JuS" "Veraison"   </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Listes des variables sélectionnées pour le critère R2_ajusté</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which</span>(model.full.summary<span class="sc">$</span>which[max.r2ajuste, ]<span class="sc">==</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "(Intercept)"         "AN"                  "NbJ10_15JJ"         
[4] "SommeTs10JJ"         "SommeTs10JuS"        "SommeRayonnementJuS"
[7] "NbJ15_20JuS"         "Veraison"           </code></pre>
</div>
</div>
<p>Dans la sortie précédente on remarque que les variables (<code>AN</code>, <code>NbJ20_25JuS</code>, <code>Veraison</code>) sélectionnés par la minimisation du critère <span class="math inline">BIC</span> sont identiques à celles sélectionnées par le critère <span class="math inline">C_p</span> qui est équivalent au critère <span class="math inline">AIC</span>. Ces variables se retrouvent également comprises dans les variables sélectionnées à partir du critère <span class="math inline">R^{2}_{ajusté}</span> qui lui possèdent plus de variables que les deux autres modèles car plus on a de variable plus le <span class="math inline">R^{2}</span> tend à augmenter. Nous pouvons enfin constater que le modèle obtenu avec le critère <span class="math inline">BIC</span> contient 1 variable de moins que le modèle obtenu avec le critère <span class="math inline">C_{p}</span>, cela est du au fait que le critère <span class="math inline">BIC</span> pénalise un fortement les modèles contenant un nombre élevés de variables.</p>
<p>Ici nous effectuons une sélection de variable basée sur l’approche backward. Dans cette approche au lieu de faire une recherche exhaustive de toutes les modèles possibles, nous partons d’un modèle complet, puis nous retirons au fur et à mesure les variables qui semblent les moins pertinentes au regard du critère <span class="math inline">C_p</span>, qui rappelons-le est un équivalent au critère <span class="math inline">AIC</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sélection de variables avec l'approche backward</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>modelfit.bwd <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(MaMerlot <span class="sc">~</span> ., <span class="at">data =</span> vigne,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">method =</span> <span class="st">"backward"</span>, <span class="at">nvmax =</span> <span class="dv">18</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>modelfit.bwd.sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelfit.bwd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valeurs du Cp</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>cp.val.bwd <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(modelfit.bwd.sum<span class="sc">$</span>cp)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>cp.val.bwd <span class="ot">&lt;-</span> cp.val.bwd <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">index=</span><span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(cp.val.bwd))) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">cp=</span><span class="st">`</span><span class="at">modelfit.bwd.sum$cp</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombre de variables minimisant le Cp par l'approche backward</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>min.cp.bwd <span class="ot">&lt;-</span> <span class="fu">which.min</span>(modelfit.bwd.sum<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>cp.val.bwd <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(cp.val.bwd) <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> index, <span class="at">y =</span> cp)) <span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cp"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nombres de variables"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Cp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ecsa_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables sélectionnées par l'approche backward</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which</span>(modelfit.bwd.sum<span class="sc">$</span>which[min.cp.bwd, ]<span class="sc">==</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "(Intercept)" "AN"          "NbJ20_25JuS" "Veraison"   </code></pre>
</div>
</div>
<p>En utilisant cette approche backward déjà on remarque le nombre de variables minimisant <span class="math inline">C_p</span> ici 3, est différentes du nombre de variables obtenues par l’approche exhaustive 5. De plus on remarque que les variables (<code>AN</code>, <code>NbJ20_25JuS</code>, <code>Veraison</code>) sélectionnées par les 2 approches sont identiques à 2 variables près. Pour essayer de trancher et récupérer le modèle qui nous semble le plus pertinent nous effectuons une comparaison de leur <span class="math inline">R^{2}_{ajusté}</span> que nous pouvons observer dans les résultats suivants :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle obtenu par approche exhaustive sur critère Cp</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(MaMerlot<span class="sc">~</span>AN<span class="sc">+</span>NbJ10_15JJ<span class="sc">+</span>SommeTs10JJ<span class="sc">+</span>NbJ20_25JuS<span class="sc">+</span>Veraison</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>           , <span class="at">data =</span> vigne))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MaMerlot ~ AN + NbJ10_15JJ + SommeTs10JJ + NbJ20_25JuS + 
    Veraison, data = vigne)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.1323 -2.7954  0.2541  1.8652  8.5458 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -5.086e+02  1.373e+02  -3.704 0.000729 ***
AN           2.908e-01  6.878e-02   4.228 0.000161 ***
NbJ10_15JJ  -1.379e-01  6.452e-02  -2.138 0.039583 *  
SommeTs10JJ -8.938e-03  4.406e-03  -2.029 0.050162 .  
NbJ20_25JuS  2.369e-01  7.289e-02   3.251 0.002547 ** 
Veraison     9.246e-01  8.729e-02  10.593 1.84e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.507 on 35 degrees of freedom
  (7 observations effacées parce que manquantes)
Multiple R-squared:  0.885, Adjusted R-squared:  0.8686 
F-statistic: 53.88 on 5 and 35 DF,  p-value: 1.868e-15</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle obtenu par backward</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(MaMerlot<span class="sc">~</span>AN<span class="sc">+</span>NbJ20_25JuS<span class="sc">+</span>Veraison, <span class="at">data =</span> vigne))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MaMerlot ~ AN + NbJ20_25JuS + Veraison, data = vigne)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.8240 -3.1139 -0.4588  2.5578  7.9118 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -353.81047  128.78621  -2.747  0.00923 ** 
AN             0.19872    0.06135   3.239  0.00254 ** 
NbJ20_25JuS    0.19202    0.07430   2.584  0.01384 *  
Veraison       0.96434    0.07614  12.664 5.08e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.703 on 37 degrees of freedom
  (7 observations effacées parce que manquantes)
Multiple R-squared:  0.8645,    Adjusted R-squared:  0.8535 
F-statistic: 78.67 on 3 and 37 DF,  p-value: 4.046e-16</code></pre>
</div>
</div>
<p>Au regard du <span class="math inline">R^{2}_{ajusté}</span> obtenu par l’approche exhaustive qui est de <span class="math inline">0.8686</span> et celui obtenu par l’approche backward <span class="math inline">0.8535</span> il semble plus pertinent de choisir le modèle obtenu par l’approche exhaustive, mais les variables <code>NbJ10_15JJ</code> et <code>SommeTS10JJ</code> étant peu voir pas trop significatif et si on souhaite obtenir un modèle peu complexe, nous pouvons en faire abstraction et retenir le modèle avec 3 variables ( <code>AN</code>, <code>NbJ20_25JuS</code>, <code>Veraison</code>). Ainsi on a le modèle :</p>
<p><span class="math display">
Y = -353.81047 + 0.19872 \times \beta_{1} + 0.19202 \times
\beta_{1} +  0.96434 \times \beta_{2} + \epsilon
</span></p>
</section>
<section id="formule-de-prédiction-pour-les-variables-obtenus-en-juin" class="level1">
<h1>2.3. Formule de prédiction pour les variables obtenus en juin</h1>
<p>Dans cette section nous utiliserons le critère <span class="math inline">C_p</span> pour effectuer notre sélection de variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Récupère toutes les mesures de Janvier à Juins</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>vigne.jj <span class="ot">&lt;-</span> vigne <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"MaMerlot"</span>), <span class="fu">ends_with</span>(<span class="st">"JJ"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle complet avec les variables de juin</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>modelfull.jj <span class="ot">&lt;-</span> <span class="fu">lm</span>(MaMerlot <span class="sc">~</span> ., <span class="at">data =</span> vigne.jj)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelfull.jj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MaMerlot ~ ., data = vigne.jj)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.0208  -4.8813   0.0454   3.8375   9.8516 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          3.406e+02  2.376e+01  14.335 1.77e-15 ***
NbJrs30JJ           -1.080e+00  6.040e-01  -1.789  0.08316 .  
NbJ25_30JJ          -1.535e+00  5.051e-01  -3.039  0.00471 ** 
NbJ20_25JJ          -8.626e-01  3.528e-01  -2.445  0.02015 *  
NbJ15_20JJ          -4.332e-01  2.620e-01  -1.654  0.10800    
NbJ10_15JJ          -2.093e-01  1.441e-01  -1.453  0.15601    
SommeTs10JJ          2.056e-02  1.748e-02   1.176  0.24824    
SommePluviometrieJJ -8.591e-03  1.057e-02  -0.813  0.42241    
SommeRayonnementJJ  -1.279e-04  1.029e-04  -1.243  0.22281    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.81 on 32 degrees of freedom
  (7 observations effacées parce que manquantes)
Multiple R-squared:  0.7115,    Adjusted R-squared:  0.6394 
F-statistic: 9.865 on 8 and 32 DF,  p-value: 8.642e-07</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sélection de variable pour obtenir un meilleur modèle</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>modelbwd.jj <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(MaMerlot <span class="sc">~</span> ., <span class="at">data =</span> vigne.jj, </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">method =</span> <span class="st">"backward"</span>, <span class="at">nvmax =</span> <span class="dv">9</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>modelbwd.jj.sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelbwd.jj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombre de variable minimisant le Cp</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(modelbwd.jj.sum<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables sélectionnés après minimisation du critère Cp</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which</span>(modelbwd.jj.sum<span class="sc">$</span>which[<span class="dv">4</span>, ]<span class="sc">==</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "(Intercept)"        "NbJrs30JJ"          "NbJ25_30JJ"        
[4] "NbJ20_25JJ"         "SommeRayonnementJJ"</code></pre>
</div>
</div>
<p>Après avoir effectué notre procédure de sélection de variable par la méthode backward on remarque que seuls 4 variables sont retenues il s’agit des variables <code>NbJrs30JJ</code>, <code>NbJ25_30JJ</code>, <code>NbJ20_25JJ</code>, <code>SommeRayonnementJJ</code>. La variable n’étant pas significatif dans le modèle nous avions décidé de la retiré de notre modèle final.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimation du modèle finale après sélection</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co"># NbJrs30JJ + SommeRayonnementJJ</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>modelfinal.jj <span class="ot">&lt;-</span> <span class="fu">lm</span>(MaMerlot <span class="sc">~</span> NbJ25_30JJ <span class="sc">+</span> NbJ20_25JJ <span class="sc">+</span> SommeRayonnementJJ,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> vigne.jj)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelfinal.jj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MaMerlot ~ NbJ25_30JJ + NbJ20_25JJ + SommeRayonnementJJ, 
    data = vigne.jj)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.8428  -4.5505  -0.0648   4.4406  10.3050 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         3.271e+02  1.507e+01  21.700  &lt; 2e-16 ***
NbJ25_30JJ         -1.042e+00  2.243e-01  -4.644 4.21e-05 ***
NbJ20_25JJ         -4.666e-01  1.482e-01  -3.149  0.00324 ** 
SommeRayonnementJJ -1.795e-04  8.504e-05  -2.111  0.04163 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.847 on 37 degrees of freedom
  (7 observations effacées parce que manquantes)
Multiple R-squared:  0.6622,    Adjusted R-squared:  0.6348 
F-statistic: 24.18 on 3 and 37 DF,  p-value: 7.788e-09</code></pre>
</div>
</div>
</section>
<section id="prédiction-pour-les-valeurs-de-2001-à-2007" class="level1">
<h1>2.4. Prédiction pour les valeurs de 2001 à 2007</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrage et selection des variable pour la prédiction</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>vigne.pred <span class="ot">&lt;-</span> vigne <span class="sc">%&gt;%</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(AN, MaMerlot, NbJrs30JJ, NbJ25_30JJ, NbJ20_25JJ,SommeRayonnementJJ))<span class="sc">%&gt;%</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>           <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(NbJrs30JJ, NbJ25_30JJ, NbJ20_25JJ,SommeRayonnementJJ),</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">~</span><span class="fu">replace_na</span>(., <span class="fu">mean</span>(., <span class="at">na.rm=</span><span class="cn">TRUE</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(AN <span class="sc">&gt;</span> <span class="dv">2000</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(MaMerlot))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Affichage des valeurs à prédire</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vigne.pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
     AN NbJrs30JJ NbJ25_30JJ NbJ20_25JJ SommeRayonnementJJ
  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;              &lt;dbl&gt;
1  2001      4          11         29               213523
2  2002      2          12         16               212923
3  2003     10          16         33               229947
4  2004      1.94       11.3       25.7             202958
5  2005      6          21         32               225297
6  2006      8          14         21               227747</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prévision des valeurs futurs</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelfinal.jj, vigne.pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>pred_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">gsub</span>(<span class="st">" "</span>, <span class="st">""</span>, <span class="fu">paste</span>(<span class="fu">as.character</span>(vigne.pred<span class="sc">$</span>AN),</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"/01/01"</span>)))<span class="sc">+</span>pred</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pred_date) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"2001"</span>, <span class="st">"2002"</span>, <span class="st">"2003"</span>, <span class="st">"2004"</span>, <span class="st">"2005"</span>, <span class="st">"2006"</span>, <span class="st">"2007"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>pred_date <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pred_date) <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">date_predite=</span>pred_date)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>pred_date<span class="sc">$</span>date_reel <span class="ot">&lt;-</span> <span class="fu">as.Date</span>((<span class="fu">c</span>(<span class="st">"2001-09-24"</span>, <span class="st">"2002-09-27"</span>, <span class="st">"2003-08-21"</span>,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"2004-09-14"</span>, <span class="st">"2005-08-29"</span>, <span class="st">"2006-09-05"</span>,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"2007-09-14"</span>)))</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>pred_date<span class="sc">$</span>erreur_absolue <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">21</span>, <span class="dv">9</span>, <span class="dv">9</span>, <span class="dv">14</span>, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(pred_date, <span class="at">caption =</span> <span class="st">"Prédiction du modèle"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">full_width =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Prédiction du modèle</caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> date_predite </th>
   <th style="text-align:left;"> date_reel </th>
   <th style="text-align:right;"> erreur_absolue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 2001 </td>
   <td style="text-align:left;"> 2001-09-21 </td>
   <td style="text-align:left;"> 2001-09-24 </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2002 </td>
   <td style="text-align:left;"> 2002-09-26 </td>
   <td style="text-align:left;"> 2002-09-27 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2003 </td>
   <td style="text-align:left;"> 2003-09-11 </td>
   <td style="text-align:left;"> 2003-08-21 </td>
   <td style="text-align:right;"> 21 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2004 </td>
   <td style="text-align:left;"> 2004-09-23 </td>
   <td style="text-align:left;"> 2004-09-14 </td>
   <td style="text-align:right;"> 9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2005 </td>
   <td style="text-align:left;"> 2005-09-07 </td>
   <td style="text-align:left;"> 2005-08-29 </td>
   <td style="text-align:right;"> 9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2006 </td>
   <td style="text-align:left;"> 2006-09-19 </td>
   <td style="text-align:left;"> 2006-09-05 </td>
   <td style="text-align:right;"> 14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2007 </td>
   <td style="text-align:left;"> 2007-09-12 </td>
   <td style="text-align:left;"> 2007-09-14 </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparaison des valeurs observés et celles prédite</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>plotting_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">annee =</span> vigne.pred<span class="sc">$</span>AN, </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">predite =</span> pred, </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">reel =</span> <span class="fu">yday</span>(pred_date<span class="sc">$</span>date_reel))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>plotting_data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>annee))<span class="sc">+</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span> pred), </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">color =</span> <span class="st">"#9460D0"</span>)<span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span> reel), </span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">color =</span> <span class="st">"#65BE64"</span>)<span class="sc">+</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">y =</span> <span class="st">"Date de maturation"</span>)<span class="sc">+</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ecsa_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Au travers des différents modèles que nous avons proposés, trois variables explicatives semblent faire varier de manière significative la date de maturation du merlot : <code>Nbr25_30JJ</code> <code>Nbr20-25JJ</code> et <code>SommeRayonnementJJ</code>. Toutes les estimations de ces coefficients étant négatives, de telle manière à ce que plus ces variables sont élevées plus la date de maturation sera tôt.</p>
<p>On en déduit que la date de maturation du merlot se joue surtout sur la période de janvier à juin. Plus on a des températures élevées durant cette période, avec un fort rayonnement, plus la maturation aura lieu tôt.</p>
<p>Pour ce qui est des valeurs de prédiction, notre modèle en a trouvé aucune exactement. Cependant, elles appartiennent aux intervalles de prédiction liées aux dates que nous avons prédites. Seulement l’année 2003, où il y a eu une longue période de canicule qui a accéléré la maturation du merlot.</p>
<p>Notre modèle de prédiction ne pourra pas perdurer dans le temps. Car notre jeu de données reste limité en matière d’information, pour pallier aux différents facteurs évoluant et faisant varier la date de maturation. Il ne prend pas en compte les changements climatiques (exemple de 2003 avec la canicule), ni les différents types de pollution pouvant impacter le merlot (pollution des sols).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>